// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CCotizacionDetalle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PROYCUATRO {

  /// <summary>Holder for reflection information generated from CCotizacionDetalle.proto</summary>
  public static partial class CCotizacionDetalleReflection {

    #region Descriptor
    /// <summary>File descriptor for CCotizacionDetalle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CCotizacionDetalleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhDQ290aXphY2lvbkRldGFsbGUucHJvdG8ixwEKD0NDb3RpemFjaW9uRGV0",
            "YRITCgtjb2RfZW1wcmVzYRgBIAEoCRIWCg5udW1fY290aXphY2lvbhgCIAEo",
            "CRIeChZudW1fY290aXphY2lvbl9kZXRhbGxlGAMgASgJEhQKDG51bV9jYW50",
            "aWRhZBgEIAEoCRIUCgxudW1fcHJvZHVjdG8YBSABKAkSFAoMbm9tX3Byb2R1",
            "Y3RvGAYgASgJEhAKCEVtYmFsYWplGAcgASgJEhMKC29ic191c3VhcmlvGAgg",
            "ASgJIoYBChlHZXRDQ290aXphY2lvbkRldGFSZXF1ZXN0EhQKDHBjb2RfZW1w",
            "cmVzYRgBIAEoCRIcChRwY29kX3VzdWFyaW9fd2luZG93cxgCIAEoCRIXCg9w",
            "bnVtX2NvdGl6YWNpb24YAyABKAkSHAoUcG51bV9jb3RpemFjaW9uX2RldGEY",
            "BCABKAkifAoaR2V0Q0NvdGl6YWNpb25EZXRhUmVzcG9uc2USLgoUQ0NvdGl6",
            "YWNpb25EZXRhT3JkZW4YASABKAsyEC5DQ290aXphY2lvbkRldGESFgoOcGVy",
            "cm9yX3RlY25pY28YAiABKAkSFgoOcGVycm9yX3VzdWFyaW8YAyABKAkybgoZ",
            "Q0NvdGl6YWNpb25EZXRhbGxlU2VydmljZRJRChRHZXRDb3RpemFjaW9uRGV0",
            "YWxsZRIaLkdldENDb3RpemFjaW9uRGV0YVJlcXVlc3QaGy5HZXRDQ290aXph",
            "Y2lvbkRldGFSZXNwb25zZTABQgqqAgdQUk9ZRE9TYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.CCotizacionDeta), global::PROYCUATRO.CCotizacionDeta.Parser, new[]{ "CodEmpresa", "NumCotizacion", "NumCotizacionDetalle", "NumCantidad", "NumProducto", "NomProducto", "Embalaje", "ObsUsuario" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCCotizacionDetaRequest), global::PROYCUATRO.GetCCotizacionDetaRequest.Parser, new[]{ "PcodEmpresa", "PcodUsuarioWindows", "PnumCotizacion", "PnumCotizacionDeta" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCCotizacionDetaResponse), global::PROYCUATRO.GetCCotizacionDetaResponse.Parser, new[]{ "CCotizacionDetaOrden", "PerrorTecnico", "PerrorUsuario" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CCotizacionDeta : pb::IMessage<CCotizacionDeta> {
    private static readonly pb::MessageParser<CCotizacionDeta> _parser = new pb::MessageParser<CCotizacionDeta>(() => new CCotizacionDeta());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CCotizacionDeta> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CCotizacionDetalleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CCotizacionDeta() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CCotizacionDeta(CCotizacionDeta other) : this() {
      codEmpresa_ = other.codEmpresa_;
      numCotizacion_ = other.numCotizacion_;
      numCotizacionDetalle_ = other.numCotizacionDetalle_;
      numCantidad_ = other.numCantidad_;
      numProducto_ = other.numProducto_;
      nomProducto_ = other.nomProducto_;
      embalaje_ = other.embalaje_;
      obsUsuario_ = other.obsUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CCotizacionDeta Clone() {
      return new CCotizacionDeta(this);
    }

    /// <summary>Field number for the "cod_empresa" field.</summary>
    public const int CodEmpresaFieldNumber = 1;
    private string codEmpresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodEmpresa {
      get { return codEmpresa_; }
      set {
        codEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_cotizacion" field.</summary>
    public const int NumCotizacionFieldNumber = 2;
    private string numCotizacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumCotizacion {
      get { return numCotizacion_; }
      set {
        numCotizacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_cotizacion_detalle" field.</summary>
    public const int NumCotizacionDetalleFieldNumber = 3;
    private string numCotizacionDetalle_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumCotizacionDetalle {
      get { return numCotizacionDetalle_; }
      set {
        numCotizacionDetalle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_cantidad" field.</summary>
    public const int NumCantidadFieldNumber = 4;
    private string numCantidad_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumCantidad {
      get { return numCantidad_; }
      set {
        numCantidad_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_producto" field.</summary>
    public const int NumProductoFieldNumber = 5;
    private string numProducto_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumProducto {
      get { return numProducto_; }
      set {
        numProducto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nom_producto" field.</summary>
    public const int NomProductoFieldNumber = 6;
    private string nomProducto_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NomProducto {
      get { return nomProducto_; }
      set {
        nomProducto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Embalaje" field.</summary>
    public const int EmbalajeFieldNumber = 7;
    private string embalaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Embalaje {
      get { return embalaje_; }
      set {
        embalaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "obs_usuario" field.</summary>
    public const int ObsUsuarioFieldNumber = 8;
    private string obsUsuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ObsUsuario {
      get { return obsUsuario_; }
      set {
        obsUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CCotizacionDeta);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CCotizacionDeta other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodEmpresa != other.CodEmpresa) return false;
      if (NumCotizacion != other.NumCotizacion) return false;
      if (NumCotizacionDetalle != other.NumCotizacionDetalle) return false;
      if (NumCantidad != other.NumCantidad) return false;
      if (NumProducto != other.NumProducto) return false;
      if (NomProducto != other.NomProducto) return false;
      if (Embalaje != other.Embalaje) return false;
      if (ObsUsuario != other.ObsUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodEmpresa.Length != 0) hash ^= CodEmpresa.GetHashCode();
      if (NumCotizacion.Length != 0) hash ^= NumCotizacion.GetHashCode();
      if (NumCotizacionDetalle.Length != 0) hash ^= NumCotizacionDetalle.GetHashCode();
      if (NumCantidad.Length != 0) hash ^= NumCantidad.GetHashCode();
      if (NumProducto.Length != 0) hash ^= NumProducto.GetHashCode();
      if (NomProducto.Length != 0) hash ^= NomProducto.GetHashCode();
      if (Embalaje.Length != 0) hash ^= Embalaje.GetHashCode();
      if (ObsUsuario.Length != 0) hash ^= ObsUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodEmpresa);
      }
      if (NumCotizacion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumCotizacion);
      }
      if (NumCotizacionDetalle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumCotizacionDetalle);
      }
      if (NumCantidad.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumCantidad);
      }
      if (NumProducto.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumProducto);
      }
      if (NomProducto.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(NomProducto);
      }
      if (Embalaje.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Embalaje);
      }
      if (ObsUsuario.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ObsUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodEmpresa);
      }
      if (NumCotizacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumCotizacion);
      }
      if (NumCotizacionDetalle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumCotizacionDetalle);
      }
      if (NumCantidad.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumCantidad);
      }
      if (NumProducto.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumProducto);
      }
      if (NomProducto.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NomProducto);
      }
      if (Embalaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Embalaje);
      }
      if (ObsUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObsUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CCotizacionDeta other) {
      if (other == null) {
        return;
      }
      if (other.CodEmpresa.Length != 0) {
        CodEmpresa = other.CodEmpresa;
      }
      if (other.NumCotizacion.Length != 0) {
        NumCotizacion = other.NumCotizacion;
      }
      if (other.NumCotizacionDetalle.Length != 0) {
        NumCotizacionDetalle = other.NumCotizacionDetalle;
      }
      if (other.NumCantidad.Length != 0) {
        NumCantidad = other.NumCantidad;
      }
      if (other.NumProducto.Length != 0) {
        NumProducto = other.NumProducto;
      }
      if (other.NomProducto.Length != 0) {
        NomProducto = other.NomProducto;
      }
      if (other.Embalaje.Length != 0) {
        Embalaje = other.Embalaje;
      }
      if (other.ObsUsuario.Length != 0) {
        ObsUsuario = other.ObsUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            NumCotizacion = input.ReadString();
            break;
          }
          case 26: {
            NumCotizacionDetalle = input.ReadString();
            break;
          }
          case 34: {
            NumCantidad = input.ReadString();
            break;
          }
          case 42: {
            NumProducto = input.ReadString();
            break;
          }
          case 50: {
            NomProducto = input.ReadString();
            break;
          }
          case 58: {
            Embalaje = input.ReadString();
            break;
          }
          case 66: {
            ObsUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetCCotizacionDetaRequest : pb::IMessage<GetCCotizacionDetaRequest> {
    private static readonly pb::MessageParser<GetCCotizacionDetaRequest> _parser = new pb::MessageParser<GetCCotizacionDetaRequest>(() => new GetCCotizacionDetaRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCCotizacionDetaRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CCotizacionDetalleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaRequest(GetCCotizacionDetaRequest other) : this() {
      pcodEmpresa_ = other.pcodEmpresa_;
      pcodUsuarioWindows_ = other.pcodUsuarioWindows_;
      pnumCotizacion_ = other.pnumCotizacion_;
      pnumCotizacionDeta_ = other.pnumCotizacionDeta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaRequest Clone() {
      return new GetCCotizacionDetaRequest(this);
    }

    /// <summary>Field number for the "pcod_empresa" field.</summary>
    public const int PcodEmpresaFieldNumber = 1;
    private string pcodEmpresa_ = "";
    /// <summary>
    /// Codigo de empresa referenciada del core para el que se ejecuta el proceso,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodEmpresa {
      get { return pcodEmpresa_; }
      set {
        pcodEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pcod_usuario_windows" field.</summary>
    public const int PcodUsuarioWindowsFieldNumber = 2;
    private string pcodUsuarioWindows_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodUsuarioWindows {
      get { return pcodUsuarioWindows_; }
      set {
        pcodUsuarioWindows_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pnum_cotizacion" field.</summary>
    public const int PnumCotizacionFieldNumber = 3;
    private string pnumCotizacion_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PnumCotizacion {
      get { return pnumCotizacion_; }
      set {
        pnumCotizacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pnum_cotizacion_deta" field.</summary>
    public const int PnumCotizacionDetaFieldNumber = 4;
    private string pnumCotizacionDeta_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PnumCotizacionDeta {
      get { return pnumCotizacionDeta_; }
      set {
        pnumCotizacionDeta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCCotizacionDetaRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCCotizacionDetaRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PcodEmpresa != other.PcodEmpresa) return false;
      if (PcodUsuarioWindows != other.PcodUsuarioWindows) return false;
      if (PnumCotizacion != other.PnumCotizacion) return false;
      if (PnumCotizacionDeta != other.PnumCotizacionDeta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PcodEmpresa.Length != 0) hash ^= PcodEmpresa.GetHashCode();
      if (PcodUsuarioWindows.Length != 0) hash ^= PcodUsuarioWindows.GetHashCode();
      if (PnumCotizacion.Length != 0) hash ^= PnumCotizacion.GetHashCode();
      if (PnumCotizacionDeta.Length != 0) hash ^= PnumCotizacionDeta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PcodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PcodUsuarioWindows);
      }
      if (PnumCotizacion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PnumCotizacion);
      }
      if (PnumCotizacionDeta.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PnumCotizacionDeta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PcodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodUsuarioWindows);
      }
      if (PnumCotizacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PnumCotizacion);
      }
      if (PnumCotizacionDeta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PnumCotizacionDeta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCCotizacionDetaRequest other) {
      if (other == null) {
        return;
      }
      if (other.PcodEmpresa.Length != 0) {
        PcodEmpresa = other.PcodEmpresa;
      }
      if (other.PcodUsuarioWindows.Length != 0) {
        PcodUsuarioWindows = other.PcodUsuarioWindows;
      }
      if (other.PnumCotizacion.Length != 0) {
        PnumCotizacion = other.PnumCotizacion;
      }
      if (other.PnumCotizacionDeta.Length != 0) {
        PnumCotizacionDeta = other.PnumCotizacionDeta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PcodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            PcodUsuarioWindows = input.ReadString();
            break;
          }
          case 26: {
            PnumCotizacion = input.ReadString();
            break;
          }
          case 34: {
            PnumCotizacionDeta = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetCCotizacionDetaResponse : pb::IMessage<GetCCotizacionDetaResponse> {
    private static readonly pb::MessageParser<GetCCotizacionDetaResponse> _parser = new pb::MessageParser<GetCCotizacionDetaResponse>(() => new GetCCotizacionDetaResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCCotizacionDetaResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CCotizacionDetalleReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaResponse(GetCCotizacionDetaResponse other) : this() {
      cCotizacionDetaOrden_ = other.cCotizacionDetaOrden_ != null ? other.cCotizacionDetaOrden_.Clone() : null;
      perrorTecnico_ = other.perrorTecnico_;
      perrorUsuario_ = other.perrorUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCCotizacionDetaResponse Clone() {
      return new GetCCotizacionDetaResponse(this);
    }

    /// <summary>Field number for the "CCotizacionDetaOrden" field.</summary>
    public const int CCotizacionDetaOrdenFieldNumber = 1;
    private global::PROYCUATRO.CCotizacionDeta cCotizacionDetaOrden_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.CCotizacionDeta CCotizacionDetaOrden {
      get { return cCotizacionDetaOrden_; }
      set {
        cCotizacionDetaOrden_ = value;
      }
    }

    /// <summary>Field number for the "perror_tecnico" field.</summary>
    public const int PerrorTecnicoFieldNumber = 2;
    private string perrorTecnico_ = "";
    /// <summary>
    /// Mensaje de error técnico del error ocurrido. Si todo está bien se retorna el valor 000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorTecnico {
      get { return perrorTecnico_; }
      set {
        perrorTecnico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perror_usuario" field.</summary>
    public const int PerrorUsuarioFieldNumber = 3;
    private string perrorUsuario_ = "";
    /// <summary>
    /// En caso de ocurrir un error, se retorna el mensaje en len
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorUsuario {
      get { return perrorUsuario_; }
      set {
        perrorUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCCotizacionDetaResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCCotizacionDetaResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CCotizacionDetaOrden, other.CCotizacionDetaOrden)) return false;
      if (PerrorTecnico != other.PerrorTecnico) return false;
      if (PerrorUsuario != other.PerrorUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cCotizacionDetaOrden_ != null) hash ^= CCotizacionDetaOrden.GetHashCode();
      if (PerrorTecnico.Length != 0) hash ^= PerrorTecnico.GetHashCode();
      if (PerrorUsuario.Length != 0) hash ^= PerrorUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cCotizacionDetaOrden_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CCotizacionDetaOrden);
      }
      if (PerrorTecnico.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PerrorUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cCotizacionDetaOrden_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CCotizacionDetaOrden);
      }
      if (PerrorTecnico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCCotizacionDetaResponse other) {
      if (other == null) {
        return;
      }
      if (other.cCotizacionDetaOrden_ != null) {
        if (cCotizacionDetaOrden_ == null) {
          CCotizacionDetaOrden = new global::PROYCUATRO.CCotizacionDeta();
        }
        CCotizacionDetaOrden.MergeFrom(other.CCotizacionDetaOrden);
      }
      if (other.PerrorTecnico.Length != 0) {
        PerrorTecnico = other.PerrorTecnico;
      }
      if (other.PerrorUsuario.Length != 0) {
        PerrorUsuario = other.PerrorUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (cCotizacionDetaOrden_ == null) {
              CCotizacionDetaOrden = new global::PROYCUATRO.CCotizacionDeta();
            }
            input.ReadMessage(CCotizacionDetaOrden);
            break;
          }
          case 18: {
            PerrorTecnico = input.ReadString();
            break;
          }
          case 26: {
            PerrorUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
