// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CCotizacionDetalle.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PROYCUATRO {
  public static partial class CCotizacionDetalleService
  {
    static readonly string __ServiceName = "CCotizacionDetalleService";

    static readonly grpc::Marshaller<global::PROYCUATRO.GetCCotizacionDetaRequest> __Marshaller_GetCCotizacionDetaRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.GetCCotizacionDetaRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PROYCUATRO.GetCCotizacionDetaResponse> __Marshaller_GetCCotizacionDetaResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.GetCCotizacionDetaResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PROYCUATRO.GetCCotizacionDetaRequest, global::PROYCUATRO.GetCCotizacionDetaResponse> __Method_GetCotizacionDetalle = new grpc::Method<global::PROYCUATRO.GetCCotizacionDetaRequest, global::PROYCUATRO.GetCCotizacionDetaResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetCotizacionDetalle",
        __Marshaller_GetCCotizacionDetaRequest,
        __Marshaller_GetCCotizacionDetaResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PROYCUATRO.CCotizacionDetalleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CCotizacionDetalleService</summary>
    [grpc::BindServiceMethod(typeof(CCotizacionDetalleService), "BindService")]
    public abstract partial class CCotizacionDetalleServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetCotizacionDetalle(global::PROYCUATRO.GetCCotizacionDetaRequest request, grpc::IServerStreamWriter<global::PROYCUATRO.GetCCotizacionDetaResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CCotizacionDetalleService</summary>
    public partial class CCotizacionDetalleServiceClient : grpc::ClientBase<CCotizacionDetalleServiceClient>
    {
      /// <summary>Creates a new client for CCotizacionDetalleService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CCotizacionDetalleServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CCotizacionDetalleService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CCotizacionDetalleServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CCotizacionDetalleServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CCotizacionDetalleServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PROYCUATRO.GetCCotizacionDetaResponse> GetCotizacionDetalle(global::PROYCUATRO.GetCCotizacionDetaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCotizacionDetalle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PROYCUATRO.GetCCotizacionDetaResponse> GetCotizacionDetalle(global::PROYCUATRO.GetCCotizacionDetaRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetCotizacionDetalle, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CCotizacionDetalleServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CCotizacionDetalleServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CCotizacionDetalleServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCotizacionDetalle, serviceImpl.GetCotizacionDetalle).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CCotizacionDetalleServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCotizacionDetalle, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::PROYCUATRO.GetCCotizacionDetaRequest, global::PROYCUATRO.GetCCotizacionDetaResponse>(serviceImpl.GetCotizacionDetalle));
    }

  }
}
#endregion
