// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CCotizaciones.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PROYCUATRO {
  public static partial class CCotizacionesService
  {
    static readonly string __ServiceName = "CCotizacionesService";

    static readonly grpc::Marshaller<global::PROYCUATRO.GetCCotizacionRequest> __Marshaller_GetCCotizacionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.GetCCotizacionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PROYCUATRO.GetCCotizacionResponse> __Marshaller_GetCCotizacionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.GetCCotizacionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PROYCUATRO.GetCCotizacionRequest, global::PROYCUATRO.GetCCotizacionResponse> __Method_GetCotizaciones = new grpc::Method<global::PROYCUATRO.GetCCotizacionRequest, global::PROYCUATRO.GetCCotizacionResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetCotizaciones",
        __Marshaller_GetCCotizacionRequest,
        __Marshaller_GetCCotizacionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PROYCUATRO.CCotizacionesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CCotizacionesService</summary>
    [grpc::BindServiceMethod(typeof(CCotizacionesService), "BindService")]
    public abstract partial class CCotizacionesServiceBase
    {
      public virtual global::System.Threading.Tasks.Task GetCotizaciones(global::PROYCUATRO.GetCCotizacionRequest request, grpc::IServerStreamWriter<global::PROYCUATRO.GetCCotizacionResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CCotizacionesService</summary>
    public partial class CCotizacionesServiceClient : grpc::ClientBase<CCotizacionesServiceClient>
    {
      /// <summary>Creates a new client for CCotizacionesService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CCotizacionesServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CCotizacionesService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CCotizacionesServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CCotizacionesServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CCotizacionesServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PROYCUATRO.GetCCotizacionResponse> GetCotizaciones(global::PROYCUATRO.GetCCotizacionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCotizaciones(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PROYCUATRO.GetCCotizacionResponse> GetCotizaciones(global::PROYCUATRO.GetCCotizacionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetCotizaciones, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CCotizacionesServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CCotizacionesServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CCotizacionesServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCotizaciones, serviceImpl.GetCotizaciones).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CCotizacionesServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCotizaciones, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::PROYCUATRO.GetCCotizacionRequest, global::PROYCUATRO.GetCCotizacionResponse>(serviceImpl.GetCotizaciones));
    }

  }
}
#endregion
