// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CListaAdjuntos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PROYCUATRO {

  /// <summary>Holder for reflection information generated from CListaAdjuntos.proto</summary>
  public static partial class CListaAdjuntosReflection {

    #region Descriptor
    /// <summary>File descriptor for CListaAdjuntos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CListaAdjuntosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDTGlzdGFBZGp1bnRvcy5wcm90byLZAQoOQ0FkanVudG9zT3JkZW4SEwoL",
            "Y29kX2VtcHJlc2EYASABKAkSGAoQbnVtX29yZGVuX2NvbXByYRgCIAEoCRIT",
            "CgtudW1fYXJjaGl2bxgDIAEoCRIVCg1jb2RfZG9jdW1lbnRvGAQgASgJEhYK",
            "DnRpcG9fZG9jdW1lbnRvGAUgASgJEhMKC25vbV9hcmNoaXZvGAYgASgJEhMK",
            "C3J1dF9hcmNoaXZvGAcgASgJEhQKDHVzcl9hZGljaW9uYRgIIAEoCRIUCgxm",
            "ZWNfYWRpY2lvbmEYCSABKAkiYwoTR2V0Q0FkanVudG9zUmVxdWVzdBIUCgxw",
            "Y29kX2VtcHJlc2EYASABKAkSHAoUcGNvZF91c3VhcmlvX3dpbmRvd3MYAiAB",
            "KAkSGAoQbnVtX29yZGVuX2NvbXByYRgDIAEoCSJqChRHZXRDQWRqdW50b3NS",
            "ZXNwb25zZRIiCglDQWRqdW50b3MYASABKAsyDy5DQWRqdW50b3NPcmRlbhIW",
            "Cg5wZXJyb3JfdGVjbmljbxgCIAEoCRIWCg5wZXJyb3JfdXN1YXJpbxgDIAEo",
            "CTJVChVDTGlzdGFBZGp1bnRvc1NlcnZpY2USPAoLR2V0QWRqdW50b3MSFC5H",
            "ZXRDQWRqdW50b3NSZXF1ZXN0GhUuR2V0Q0FkanVudG9zUmVzcG9uc2UwAUIK",
            "qgIHUFJPWURPU2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.CAdjuntosOrden), global::PROYCUATRO.CAdjuntosOrden.Parser, new[]{ "CodEmpresa", "NumOrdenCompra", "NumArchivo", "CodDocumento", "TipoDocumento", "NomArchivo", "RutArchivo", "UsrAdiciona", "FecAdiciona" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCAdjuntosRequest), global::PROYCUATRO.GetCAdjuntosRequest.Parser, new[]{ "PcodEmpresa", "PcodUsuarioWindows", "NumOrdenCompra" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCAdjuntosResponse), global::PROYCUATRO.GetCAdjuntosResponse.Parser, new[]{ "CAdjuntos", "PerrorTecnico", "PerrorUsuario" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CAdjuntosOrden : pb::IMessage<CAdjuntosOrden> {
    private static readonly pb::MessageParser<CAdjuntosOrden> _parser = new pb::MessageParser<CAdjuntosOrden>(() => new CAdjuntosOrden());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CAdjuntosOrden> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAdjuntosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAdjuntosOrden() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAdjuntosOrden(CAdjuntosOrden other) : this() {
      codEmpresa_ = other.codEmpresa_;
      numOrdenCompra_ = other.numOrdenCompra_;
      numArchivo_ = other.numArchivo_;
      codDocumento_ = other.codDocumento_;
      tipoDocumento_ = other.tipoDocumento_;
      nomArchivo_ = other.nomArchivo_;
      rutArchivo_ = other.rutArchivo_;
      usrAdiciona_ = other.usrAdiciona_;
      fecAdiciona_ = other.fecAdiciona_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAdjuntosOrden Clone() {
      return new CAdjuntosOrden(this);
    }

    /// <summary>Field number for the "cod_empresa" field.</summary>
    public const int CodEmpresaFieldNumber = 1;
    private string codEmpresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodEmpresa {
      get { return codEmpresa_; }
      set {
        codEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 2;
    private string numOrdenCompra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_archivo" field.</summary>
    public const int NumArchivoFieldNumber = 3;
    private string numArchivo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumArchivo {
      get { return numArchivo_; }
      set {
        numArchivo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cod_documento" field.</summary>
    public const int CodDocumentoFieldNumber = 4;
    private string codDocumento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodDocumento {
      get { return codDocumento_; }
      set {
        codDocumento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tipo_documento" field.</summary>
    public const int TipoDocumentoFieldNumber = 5;
    private string tipoDocumento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TipoDocumento {
      get { return tipoDocumento_; }
      set {
        tipoDocumento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nom_archivo" field.</summary>
    public const int NomArchivoFieldNumber = 6;
    private string nomArchivo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NomArchivo {
      get { return nomArchivo_; }
      set {
        nomArchivo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rut_archivo" field.</summary>
    public const int RutArchivoFieldNumber = 7;
    private string rutArchivo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RutArchivo {
      get { return rutArchivo_; }
      set {
        rutArchivo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "usr_adiciona" field.</summary>
    public const int UsrAdicionaFieldNumber = 8;
    private string usrAdiciona_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UsrAdiciona {
      get { return usrAdiciona_; }
      set {
        usrAdiciona_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fec_adiciona" field.</summary>
    public const int FecAdicionaFieldNumber = 9;
    private string fecAdiciona_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FecAdiciona {
      get { return fecAdiciona_; }
      set {
        fecAdiciona_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CAdjuntosOrden);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CAdjuntosOrden other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodEmpresa != other.CodEmpresa) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      if (NumArchivo != other.NumArchivo) return false;
      if (CodDocumento != other.CodDocumento) return false;
      if (TipoDocumento != other.TipoDocumento) return false;
      if (NomArchivo != other.NomArchivo) return false;
      if (RutArchivo != other.RutArchivo) return false;
      if (UsrAdiciona != other.UsrAdiciona) return false;
      if (FecAdiciona != other.FecAdiciona) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodEmpresa.Length != 0) hash ^= CodEmpresa.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (NumArchivo.Length != 0) hash ^= NumArchivo.GetHashCode();
      if (CodDocumento.Length != 0) hash ^= CodDocumento.GetHashCode();
      if (TipoDocumento.Length != 0) hash ^= TipoDocumento.GetHashCode();
      if (NomArchivo.Length != 0) hash ^= NomArchivo.GetHashCode();
      if (RutArchivo.Length != 0) hash ^= RutArchivo.GetHashCode();
      if (UsrAdiciona.Length != 0) hash ^= UsrAdiciona.GetHashCode();
      if (FecAdiciona.Length != 0) hash ^= FecAdiciona.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumOrdenCompra);
      }
      if (NumArchivo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumArchivo);
      }
      if (CodDocumento.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CodDocumento);
      }
      if (TipoDocumento.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TipoDocumento);
      }
      if (NomArchivo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(NomArchivo);
      }
      if (RutArchivo.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(RutArchivo);
      }
      if (UsrAdiciona.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(UsrAdiciona);
      }
      if (FecAdiciona.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FecAdiciona);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (NumArchivo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumArchivo);
      }
      if (CodDocumento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodDocumento);
      }
      if (TipoDocumento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TipoDocumento);
      }
      if (NomArchivo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NomArchivo);
      }
      if (RutArchivo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RutArchivo);
      }
      if (UsrAdiciona.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UsrAdiciona);
      }
      if (FecAdiciona.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FecAdiciona);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CAdjuntosOrden other) {
      if (other == null) {
        return;
      }
      if (other.CodEmpresa.Length != 0) {
        CodEmpresa = other.CodEmpresa;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      if (other.NumArchivo.Length != 0) {
        NumArchivo = other.NumArchivo;
      }
      if (other.CodDocumento.Length != 0) {
        CodDocumento = other.CodDocumento;
      }
      if (other.TipoDocumento.Length != 0) {
        TipoDocumento = other.TipoDocumento;
      }
      if (other.NomArchivo.Length != 0) {
        NomArchivo = other.NomArchivo;
      }
      if (other.RutArchivo.Length != 0) {
        RutArchivo = other.RutArchivo;
      }
      if (other.UsrAdiciona.Length != 0) {
        UsrAdiciona = other.UsrAdiciona;
      }
      if (other.FecAdiciona.Length != 0) {
        FecAdiciona = other.FecAdiciona;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            NumOrdenCompra = input.ReadString();
            break;
          }
          case 26: {
            NumArchivo = input.ReadString();
            break;
          }
          case 34: {
            CodDocumento = input.ReadString();
            break;
          }
          case 42: {
            TipoDocumento = input.ReadString();
            break;
          }
          case 50: {
            NomArchivo = input.ReadString();
            break;
          }
          case 58: {
            RutArchivo = input.ReadString();
            break;
          }
          case 66: {
            UsrAdiciona = input.ReadString();
            break;
          }
          case 74: {
            FecAdiciona = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// client asking for all locations 
  /// </summary>
  public sealed partial class GetCAdjuntosRequest : pb::IMessage<GetCAdjuntosRequest> {
    private static readonly pb::MessageParser<GetCAdjuntosRequest> _parser = new pb::MessageParser<GetCAdjuntosRequest>(() => new GetCAdjuntosRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCAdjuntosRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAdjuntosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosRequest(GetCAdjuntosRequest other) : this() {
      pcodEmpresa_ = other.pcodEmpresa_;
      pcodUsuarioWindows_ = other.pcodUsuarioWindows_;
      numOrdenCompra_ = other.numOrdenCompra_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosRequest Clone() {
      return new GetCAdjuntosRequest(this);
    }

    /// <summary>Field number for the "pcod_empresa" field.</summary>
    public const int PcodEmpresaFieldNumber = 1;
    private string pcodEmpresa_ = "";
    /// <summary>
    /// Codigo de empresa referenciada del core para el que se ejecuta el proceso,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodEmpresa {
      get { return pcodEmpresa_; }
      set {
        pcodEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pcod_usuario_windows" field.</summary>
    public const int PcodUsuarioWindowsFieldNumber = 2;
    private string pcodUsuarioWindows_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodUsuarioWindows {
      get { return pcodUsuarioWindows_; }
      set {
        pcodUsuarioWindows_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 3;
    private string numOrdenCompra_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCAdjuntosRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCAdjuntosRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PcodEmpresa != other.PcodEmpresa) return false;
      if (PcodUsuarioWindows != other.PcodUsuarioWindows) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PcodEmpresa.Length != 0) hash ^= PcodEmpresa.GetHashCode();
      if (PcodUsuarioWindows.Length != 0) hash ^= PcodUsuarioWindows.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PcodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PcodUsuarioWindows);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumOrdenCompra);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PcodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodUsuarioWindows);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCAdjuntosRequest other) {
      if (other == null) {
        return;
      }
      if (other.PcodEmpresa.Length != 0) {
        PcodEmpresa = other.PcodEmpresa;
      }
      if (other.PcodUsuarioWindows.Length != 0) {
        PcodUsuarioWindows = other.PcodUsuarioWindows;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PcodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            PcodUsuarioWindows = input.ReadString();
            break;
          }
          case 26: {
            NumOrdenCompra = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// response with all locations 
  /// </summary>
  public sealed partial class GetCAdjuntosResponse : pb::IMessage<GetCAdjuntosResponse> {
    private static readonly pb::MessageParser<GetCAdjuntosResponse> _parser = new pb::MessageParser<GetCAdjuntosResponse>(() => new GetCAdjuntosResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCAdjuntosResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAdjuntosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosResponse(GetCAdjuntosResponse other) : this() {
      cAdjuntos_ = other.cAdjuntos_ != null ? other.cAdjuntos_.Clone() : null;
      perrorTecnico_ = other.perrorTecnico_;
      perrorUsuario_ = other.perrorUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAdjuntosResponse Clone() {
      return new GetCAdjuntosResponse(this);
    }

    /// <summary>Field number for the "CAdjuntos" field.</summary>
    public const int CAdjuntosFieldNumber = 1;
    private global::PROYCUATRO.CAdjuntosOrden cAdjuntos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.CAdjuntosOrden CAdjuntos {
      get { return cAdjuntos_; }
      set {
        cAdjuntos_ = value;
      }
    }

    /// <summary>Field number for the "perror_tecnico" field.</summary>
    public const int PerrorTecnicoFieldNumber = 2;
    private string perrorTecnico_ = "";
    /// <summary>
    /// Mensaje de error técnico del error ocurrido. Si todo está bien se retorna el valor 000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorTecnico {
      get { return perrorTecnico_; }
      set {
        perrorTecnico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perror_usuario" field.</summary>
    public const int PerrorUsuarioFieldNumber = 3;
    private string perrorUsuario_ = "";
    /// <summary>
    /// En caso de ocurrir un error, se retorna el mensaje en len
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorUsuario {
      get { return perrorUsuario_; }
      set {
        perrorUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCAdjuntosResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCAdjuntosResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CAdjuntos, other.CAdjuntos)) return false;
      if (PerrorTecnico != other.PerrorTecnico) return false;
      if (PerrorUsuario != other.PerrorUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cAdjuntos_ != null) hash ^= CAdjuntos.GetHashCode();
      if (PerrorTecnico.Length != 0) hash ^= PerrorTecnico.GetHashCode();
      if (PerrorUsuario.Length != 0) hash ^= PerrorUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cAdjuntos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CAdjuntos);
      }
      if (PerrorTecnico.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PerrorUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cAdjuntos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CAdjuntos);
      }
      if (PerrorTecnico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCAdjuntosResponse other) {
      if (other == null) {
        return;
      }
      if (other.cAdjuntos_ != null) {
        if (cAdjuntos_ == null) {
          CAdjuntos = new global::PROYCUATRO.CAdjuntosOrden();
        }
        CAdjuntos.MergeFrom(other.CAdjuntos);
      }
      if (other.PerrorTecnico.Length != 0) {
        PerrorTecnico = other.PerrorTecnico;
      }
      if (other.PerrorUsuario.Length != 0) {
        PerrorUsuario = other.PerrorUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (cAdjuntos_ == null) {
              CAdjuntos = new global::PROYCUATRO.CAdjuntosOrden();
            }
            input.ReadMessage(CAdjuntos);
            break;
          }
          case 18: {
            PerrorTecnico = input.ReadString();
            break;
          }
          case 26: {
            PerrorUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
