// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CListaAprobadores.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PROYCUATRO {

  /// <summary>Holder for reflection information generated from CListaAprobadores.proto</summary>
  public static partial class CListaAprobadoresReflection {

    #region Descriptor
    /// <summary>File descriptor for CListaAprobadores.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CListaAprobadoresReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDTGlzdGFBcHJvYmFkb3Jlcy5wcm90byKtAQoRQ0Fwcm9iYWRvcmVzT3Jk",
            "ZW4SEwoLY29kX2VtcHJlc2EYASABKAkSGAoQbnVtX29yZGVuX2NvbXByYRgC",
            "IAEoCRITCgtjb2RfdXN1YXJpbxgDIAEoCRITCgtub21fdXN1YXJpbxgEIAEo",
            "CRIWCg5mZWNfcmVzb2x1Y2lvbhgFIAEoCRISCgpub21fZXN0YWRvGAYgASgJ",
            "EhMKC29ic191c3VhcmlvGAcgASgJImYKFkdldENBcHJvYmFkb3Jlc1JlcXVl",
            "c3QSFAoMcGNvZF9lbXByZXNhGAEgASgJEhwKFHBjb2RfdXN1YXJpb193aW5k",
            "b3dzGAIgASgJEhgKEG51bV9vcmRlbl9jb21wcmEYAyABKAkicQoXR2V0Q0Fw",
            "cm9iYWRvcmVzUmVzcG9uc2USJgoKQ0Fwcm9iYWRvchgBIAEoCzISLkNBcHJv",
            "YmFkb3Jlc09yZGVuEhYKDnBlcnJvcl90ZWNuaWNvGAIgASgJEhYKDnBlcnJv",
            "cl91c3VhcmlvGAMgASgJMmEKGENMaXN0YUFwcm9iYWRvcmVzU2VydmljZRJF",
            "Cg5HZXRBcHJvYmFkb3JlcxIXLkdldENBcHJvYmFkb3Jlc1JlcXVlc3QaGC5H",
            "ZXRDQXByb2JhZG9yZXNSZXNwb25zZTABQgqqAgdQUk9ZRE9TYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.CAprobadoresOrden), global::PROYCUATRO.CAprobadoresOrden.Parser, new[]{ "CodEmpresa", "NumOrdenCompra", "CodUsuario", "NomUsuario", "FecResolucion", "NomEstado", "ObsUsuario" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCAprobadoresRequest), global::PROYCUATRO.GetCAprobadoresRequest.Parser, new[]{ "PcodEmpresa", "PcodUsuarioWindows", "NumOrdenCompra" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetCAprobadoresResponse), global::PROYCUATRO.GetCAprobadoresResponse.Parser, new[]{ "CAprobador", "PerrorTecnico", "PerrorUsuario" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CAprobadoresOrden : pb::IMessage<CAprobadoresOrden> {
    private static readonly pb::MessageParser<CAprobadoresOrden> _parser = new pb::MessageParser<CAprobadoresOrden>(() => new CAprobadoresOrden());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CAprobadoresOrden> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAprobadoresReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAprobadoresOrden() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAprobadoresOrden(CAprobadoresOrden other) : this() {
      codEmpresa_ = other.codEmpresa_;
      numOrdenCompra_ = other.numOrdenCompra_;
      codUsuario_ = other.codUsuario_;
      nomUsuario_ = other.nomUsuario_;
      fecResolucion_ = other.fecResolucion_;
      nomEstado_ = other.nomEstado_;
      obsUsuario_ = other.obsUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CAprobadoresOrden Clone() {
      return new CAprobadoresOrden(this);
    }

    /// <summary>Field number for the "cod_empresa" field.</summary>
    public const int CodEmpresaFieldNumber = 1;
    private string codEmpresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodEmpresa {
      get { return codEmpresa_; }
      set {
        codEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 2;
    private string numOrdenCompra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cod_usuario" field.</summary>
    public const int CodUsuarioFieldNumber = 3;
    private string codUsuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodUsuario {
      get { return codUsuario_; }
      set {
        codUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nom_usuario" field.</summary>
    public const int NomUsuarioFieldNumber = 4;
    private string nomUsuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NomUsuario {
      get { return nomUsuario_; }
      set {
        nomUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fec_resolucion" field.</summary>
    public const int FecResolucionFieldNumber = 5;
    private string fecResolucion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FecResolucion {
      get { return fecResolucion_; }
      set {
        fecResolucion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nom_estado" field.</summary>
    public const int NomEstadoFieldNumber = 6;
    private string nomEstado_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NomEstado {
      get { return nomEstado_; }
      set {
        nomEstado_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "obs_usuario" field.</summary>
    public const int ObsUsuarioFieldNumber = 7;
    private string obsUsuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ObsUsuario {
      get { return obsUsuario_; }
      set {
        obsUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CAprobadoresOrden);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CAprobadoresOrden other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodEmpresa != other.CodEmpresa) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      if (CodUsuario != other.CodUsuario) return false;
      if (NomUsuario != other.NomUsuario) return false;
      if (FecResolucion != other.FecResolucion) return false;
      if (NomEstado != other.NomEstado) return false;
      if (ObsUsuario != other.ObsUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodEmpresa.Length != 0) hash ^= CodEmpresa.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (CodUsuario.Length != 0) hash ^= CodUsuario.GetHashCode();
      if (NomUsuario.Length != 0) hash ^= NomUsuario.GetHashCode();
      if (FecResolucion.Length != 0) hash ^= FecResolucion.GetHashCode();
      if (NomEstado.Length != 0) hash ^= NomEstado.GetHashCode();
      if (ObsUsuario.Length != 0) hash ^= ObsUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumOrdenCompra);
      }
      if (CodUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CodUsuario);
      }
      if (NomUsuario.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NomUsuario);
      }
      if (FecResolucion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FecResolucion);
      }
      if (NomEstado.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(NomEstado);
      }
      if (ObsUsuario.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ObsUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (CodUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodUsuario);
      }
      if (NomUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NomUsuario);
      }
      if (FecResolucion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FecResolucion);
      }
      if (NomEstado.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NomEstado);
      }
      if (ObsUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObsUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CAprobadoresOrden other) {
      if (other == null) {
        return;
      }
      if (other.CodEmpresa.Length != 0) {
        CodEmpresa = other.CodEmpresa;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      if (other.CodUsuario.Length != 0) {
        CodUsuario = other.CodUsuario;
      }
      if (other.NomUsuario.Length != 0) {
        NomUsuario = other.NomUsuario;
      }
      if (other.FecResolucion.Length != 0) {
        FecResolucion = other.FecResolucion;
      }
      if (other.NomEstado.Length != 0) {
        NomEstado = other.NomEstado;
      }
      if (other.ObsUsuario.Length != 0) {
        ObsUsuario = other.ObsUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            NumOrdenCompra = input.ReadString();
            break;
          }
          case 26: {
            CodUsuario = input.ReadString();
            break;
          }
          case 34: {
            NomUsuario = input.ReadString();
            break;
          }
          case 42: {
            FecResolucion = input.ReadString();
            break;
          }
          case 50: {
            NomEstado = input.ReadString();
            break;
          }
          case 58: {
            ObsUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// client asking for all locations 
  /// </summary>
  public sealed partial class GetCAprobadoresRequest : pb::IMessage<GetCAprobadoresRequest> {
    private static readonly pb::MessageParser<GetCAprobadoresRequest> _parser = new pb::MessageParser<GetCAprobadoresRequest>(() => new GetCAprobadoresRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCAprobadoresRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAprobadoresReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresRequest(GetCAprobadoresRequest other) : this() {
      pcodEmpresa_ = other.pcodEmpresa_;
      pcodUsuarioWindows_ = other.pcodUsuarioWindows_;
      numOrdenCompra_ = other.numOrdenCompra_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresRequest Clone() {
      return new GetCAprobadoresRequest(this);
    }

    /// <summary>Field number for the "pcod_empresa" field.</summary>
    public const int PcodEmpresaFieldNumber = 1;
    private string pcodEmpresa_ = "";
    /// <summary>
    /// Codigo de empresa referenciada del core para el que se ejecuta el proceso,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodEmpresa {
      get { return pcodEmpresa_; }
      set {
        pcodEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pcod_usuario_windows" field.</summary>
    public const int PcodUsuarioWindowsFieldNumber = 2;
    private string pcodUsuarioWindows_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodUsuarioWindows {
      get { return pcodUsuarioWindows_; }
      set {
        pcodUsuarioWindows_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 3;
    private string numOrdenCompra_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCAprobadoresRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCAprobadoresRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PcodEmpresa != other.PcodEmpresa) return false;
      if (PcodUsuarioWindows != other.PcodUsuarioWindows) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PcodEmpresa.Length != 0) hash ^= PcodEmpresa.GetHashCode();
      if (PcodUsuarioWindows.Length != 0) hash ^= PcodUsuarioWindows.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PcodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PcodUsuarioWindows);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumOrdenCompra);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PcodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodUsuarioWindows);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCAprobadoresRequest other) {
      if (other == null) {
        return;
      }
      if (other.PcodEmpresa.Length != 0) {
        PcodEmpresa = other.PcodEmpresa;
      }
      if (other.PcodUsuarioWindows.Length != 0) {
        PcodUsuarioWindows = other.PcodUsuarioWindows;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PcodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            PcodUsuarioWindows = input.ReadString();
            break;
          }
          case 26: {
            NumOrdenCompra = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// response with all locations 
  /// </summary>
  public sealed partial class GetCAprobadoresResponse : pb::IMessage<GetCAprobadoresResponse> {
    private static readonly pb::MessageParser<GetCAprobadoresResponse> _parser = new pb::MessageParser<GetCAprobadoresResponse>(() => new GetCAprobadoresResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetCAprobadoresResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CListaAprobadoresReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresResponse(GetCAprobadoresResponse other) : this() {
      cAprobador_ = other.cAprobador_ != null ? other.cAprobador_.Clone() : null;
      perrorTecnico_ = other.perrorTecnico_;
      perrorUsuario_ = other.perrorUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetCAprobadoresResponse Clone() {
      return new GetCAprobadoresResponse(this);
    }

    /// <summary>Field number for the "CAprobador" field.</summary>
    public const int CAprobadorFieldNumber = 1;
    private global::PROYCUATRO.CAprobadoresOrden cAprobador_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.CAprobadoresOrden CAprobador {
      get { return cAprobador_; }
      set {
        cAprobador_ = value;
      }
    }

    /// <summary>Field number for the "perror_tecnico" field.</summary>
    public const int PerrorTecnicoFieldNumber = 2;
    private string perrorTecnico_ = "";
    /// <summary>
    /// Mensaje de error técnico del error ocurrido. Si todo está bien se retorna el valor 000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorTecnico {
      get { return perrorTecnico_; }
      set {
        perrorTecnico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perror_usuario" field.</summary>
    public const int PerrorUsuarioFieldNumber = 3;
    private string perrorUsuario_ = "";
    /// <summary>
    /// En caso de ocurrir un error, se retorna el mensaje en len
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorUsuario {
      get { return perrorUsuario_; }
      set {
        perrorUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetCAprobadoresResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetCAprobadoresResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CAprobador, other.CAprobador)) return false;
      if (PerrorTecnico != other.PerrorTecnico) return false;
      if (PerrorUsuario != other.PerrorUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cAprobador_ != null) hash ^= CAprobador.GetHashCode();
      if (PerrorTecnico.Length != 0) hash ^= PerrorTecnico.GetHashCode();
      if (PerrorUsuario.Length != 0) hash ^= PerrorUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cAprobador_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CAprobador);
      }
      if (PerrorTecnico.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PerrorUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cAprobador_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CAprobador);
      }
      if (PerrorTecnico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetCAprobadoresResponse other) {
      if (other == null) {
        return;
      }
      if (other.cAprobador_ != null) {
        if (cAprobador_ == null) {
          CAprobador = new global::PROYCUATRO.CAprobadoresOrden();
        }
        CAprobador.MergeFrom(other.CAprobador);
      }
      if (other.PerrorTecnico.Length != 0) {
        PerrorTecnico = other.PerrorTecnico;
      }
      if (other.PerrorUsuario.Length != 0) {
        PerrorUsuario = other.PerrorUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (cAprobador_ == null) {
              CAprobador = new global::PROYCUATRO.CAprobadoresOrden();
            }
            input.ReadMessage(CAprobador);
            break;
          }
          case 18: {
            PerrorTecnico = input.ReadString();
            break;
          }
          case 26: {
            PerrorUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
