// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: COrdenesCompra.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PROYCUATRO {

  /// <summary>Holder for reflection information generated from COrdenesCompra.proto</summary>
  public static partial class COrdenesCompraReflection {

    #region Descriptor
    /// <summary>File descriptor for COrdenesCompra.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static COrdenesCompraReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDT3JkZW5lc0NvbXByYS5wcm90byKeAQoNT3JkZW5lc0NvbXByYRITCgtj",
            "b2RfZW1wcmVzYRgBIAEoCRIYChBudW1fb3JkZW5fY29tcHJhGAIgASgJEhgK",
            "EHRpdF9vcmRlbl9jb21wcmEYAyABKAkSEQoJZmVjX29yZGVuGAQgASgJEhgK",
            "EG51bV9hdXRvcml6YWNpb24YBSABKAkSFwoPbnVtX2NvbXBhcmF0aXZvGAYg",
            "ASgJIkcKEUdldE9yZGVuZXNSZXF1ZXN0EhQKDHBjb2RfZW1wcmVzYRgBIAEo",
            "CRIcChRwY29kX3VzdWFyaW9fd2luZG93cxgCIAEoCSJpChJHZXRPcmRlbmVz",
            "UmVzcG9uc2USIwoLb3JkZW5jb21wcmEYASABKAsyDi5PcmRlbmVzQ29tcHJh",
            "EhYKDnBlcnJvcl90ZWNuaWNvGAIgASgJEhYKDnBlcnJvcl91c3VhcmlvGAMg",
            "ASgJMk8KFE9yZGVuZXNDb21wcmFTZXJ2aWNlEjcKCkdldE9yZGVuZXMSEi5H",
            "ZXRPcmRlbmVzUmVxdWVzdBoTLkdldE9yZGVuZXNSZXNwb25zZTABQgqqAgdQ",
            "Uk9ZRE9TYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.OrdenesCompra), global::PROYCUATRO.OrdenesCompra.Parser, new[]{ "CodEmpresa", "NumOrdenCompra", "TitOrdenCompra", "FecOrden", "NumAutorizacion", "NumComparativo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetOrdenesRequest), global::PROYCUATRO.GetOrdenesRequest.Parser, new[]{ "PcodEmpresa", "PcodUsuarioWindows" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.GetOrdenesResponse), global::PROYCUATRO.GetOrdenesResponse.Parser, new[]{ "Ordencompra", "PerrorTecnico", "PerrorUsuario" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OrdenesCompra : pb::IMessage<OrdenesCompra> {
    private static readonly pb::MessageParser<OrdenesCompra> _parser = new pb::MessageParser<OrdenesCompra>(() => new OrdenesCompra());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrdenesCompra> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.COrdenesCompraReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrdenesCompra() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrdenesCompra(OrdenesCompra other) : this() {
      codEmpresa_ = other.codEmpresa_;
      numOrdenCompra_ = other.numOrdenCompra_;
      titOrdenCompra_ = other.titOrdenCompra_;
      fecOrden_ = other.fecOrden_;
      numAutorizacion_ = other.numAutorizacion_;
      numComparativo_ = other.numComparativo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrdenesCompra Clone() {
      return new OrdenesCompra(this);
    }

    /// <summary>Field number for the "cod_empresa" field.</summary>
    public const int CodEmpresaFieldNumber = 1;
    private string codEmpresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodEmpresa {
      get { return codEmpresa_; }
      set {
        codEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 2;
    private string numOrdenCompra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tit_orden_compra" field.</summary>
    public const int TitOrdenCompraFieldNumber = 3;
    private string titOrdenCompra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TitOrdenCompra {
      get { return titOrdenCompra_; }
      set {
        titOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fec_orden" field.</summary>
    public const int FecOrdenFieldNumber = 4;
    private string fecOrden_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FecOrden {
      get { return fecOrden_; }
      set {
        fecOrden_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_autorizacion" field.</summary>
    public const int NumAutorizacionFieldNumber = 5;
    private string numAutorizacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumAutorizacion {
      get { return numAutorizacion_; }
      set {
        numAutorizacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_comparativo" field.</summary>
    public const int NumComparativoFieldNumber = 6;
    private string numComparativo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumComparativo {
      get { return numComparativo_; }
      set {
        numComparativo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrdenesCompra);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrdenesCompra other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodEmpresa != other.CodEmpresa) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      if (TitOrdenCompra != other.TitOrdenCompra) return false;
      if (FecOrden != other.FecOrden) return false;
      if (NumAutorizacion != other.NumAutorizacion) return false;
      if (NumComparativo != other.NumComparativo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodEmpresa.Length != 0) hash ^= CodEmpresa.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (TitOrdenCompra.Length != 0) hash ^= TitOrdenCompra.GetHashCode();
      if (FecOrden.Length != 0) hash ^= FecOrden.GetHashCode();
      if (NumAutorizacion.Length != 0) hash ^= NumAutorizacion.GetHashCode();
      if (NumComparativo.Length != 0) hash ^= NumComparativo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumOrdenCompra);
      }
      if (TitOrdenCompra.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TitOrdenCompra);
      }
      if (FecOrden.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FecOrden);
      }
      if (NumAutorizacion.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NumAutorizacion);
      }
      if (NumComparativo.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(NumComparativo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodEmpresa);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (TitOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitOrdenCompra);
      }
      if (FecOrden.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FecOrden);
      }
      if (NumAutorizacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumAutorizacion);
      }
      if (NumComparativo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumComparativo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrdenesCompra other) {
      if (other == null) {
        return;
      }
      if (other.CodEmpresa.Length != 0) {
        CodEmpresa = other.CodEmpresa;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      if (other.TitOrdenCompra.Length != 0) {
        TitOrdenCompra = other.TitOrdenCompra;
      }
      if (other.FecOrden.Length != 0) {
        FecOrden = other.FecOrden;
      }
      if (other.NumAutorizacion.Length != 0) {
        NumAutorizacion = other.NumAutorizacion;
      }
      if (other.NumComparativo.Length != 0) {
        NumComparativo = other.NumComparativo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            NumOrdenCompra = input.ReadString();
            break;
          }
          case 26: {
            TitOrdenCompra = input.ReadString();
            break;
          }
          case 34: {
            FecOrden = input.ReadString();
            break;
          }
          case 42: {
            NumAutorizacion = input.ReadString();
            break;
          }
          case 50: {
            NumComparativo = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// client asking for all locations 
  /// </summary>
  public sealed partial class GetOrdenesRequest : pb::IMessage<GetOrdenesRequest> {
    private static readonly pb::MessageParser<GetOrdenesRequest> _parser = new pb::MessageParser<GetOrdenesRequest>(() => new GetOrdenesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetOrdenesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.COrdenesCompraReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesRequest(GetOrdenesRequest other) : this() {
      pcodEmpresa_ = other.pcodEmpresa_;
      pcodUsuarioWindows_ = other.pcodUsuarioWindows_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesRequest Clone() {
      return new GetOrdenesRequest(this);
    }

    /// <summary>Field number for the "pcod_empresa" field.</summary>
    public const int PcodEmpresaFieldNumber = 1;
    private string pcodEmpresa_ = "";
    /// <summary>
    /// Codigo de empresa referenciada del core para el que se ejecuta el proceso,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodEmpresa {
      get { return pcodEmpresa_; }
      set {
        pcodEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pcod_usuario_windows" field.</summary>
    public const int PcodUsuarioWindowsFieldNumber = 2;
    private string pcodUsuarioWindows_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodUsuarioWindows {
      get { return pcodUsuarioWindows_; }
      set {
        pcodUsuarioWindows_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetOrdenesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetOrdenesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PcodEmpresa != other.PcodEmpresa) return false;
      if (PcodUsuarioWindows != other.PcodUsuarioWindows) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PcodEmpresa.Length != 0) hash ^= PcodEmpresa.GetHashCode();
      if (PcodUsuarioWindows.Length != 0) hash ^= PcodUsuarioWindows.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PcodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PcodUsuarioWindows);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PcodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodUsuarioWindows);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetOrdenesRequest other) {
      if (other == null) {
        return;
      }
      if (other.PcodEmpresa.Length != 0) {
        PcodEmpresa = other.PcodEmpresa;
      }
      if (other.PcodUsuarioWindows.Length != 0) {
        PcodUsuarioWindows = other.PcodUsuarioWindows;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PcodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            PcodUsuarioWindows = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// response with all locations 
  /// </summary>
  public sealed partial class GetOrdenesResponse : pb::IMessage<GetOrdenesResponse> {
    private static readonly pb::MessageParser<GetOrdenesResponse> _parser = new pb::MessageParser<GetOrdenesResponse>(() => new GetOrdenesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetOrdenesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.COrdenesCompraReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesResponse(GetOrdenesResponse other) : this() {
      ordencompra_ = other.ordencompra_ != null ? other.ordencompra_.Clone() : null;
      perrorTecnico_ = other.perrorTecnico_;
      perrorUsuario_ = other.perrorUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOrdenesResponse Clone() {
      return new GetOrdenesResponse(this);
    }

    /// <summary>Field number for the "ordencompra" field.</summary>
    public const int OrdencompraFieldNumber = 1;
    private global::PROYCUATRO.OrdenesCompra ordencompra_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.OrdenesCompra Ordencompra {
      get { return ordencompra_; }
      set {
        ordencompra_ = value;
      }
    }

    /// <summary>Field number for the "perror_tecnico" field.</summary>
    public const int PerrorTecnicoFieldNumber = 2;
    private string perrorTecnico_ = "";
    /// <summary>
    /// Mensaje de error técnico del error ocurrido. Si todo está bien se retorna el valor 000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorTecnico {
      get { return perrorTecnico_; }
      set {
        perrorTecnico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perror_usuario" field.</summary>
    public const int PerrorUsuarioFieldNumber = 3;
    private string perrorUsuario_ = "";
    /// <summary>
    /// En caso de ocurrir un error, se retorna el mensaje en len
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorUsuario {
      get { return perrorUsuario_; }
      set {
        perrorUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetOrdenesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetOrdenesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Ordencompra, other.Ordencompra)) return false;
      if (PerrorTecnico != other.PerrorTecnico) return false;
      if (PerrorUsuario != other.PerrorUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ordencompra_ != null) hash ^= Ordencompra.GetHashCode();
      if (PerrorTecnico.Length != 0) hash ^= PerrorTecnico.GetHashCode();
      if (PerrorUsuario.Length != 0) hash ^= PerrorUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ordencompra_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Ordencompra);
      }
      if (PerrorTecnico.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PerrorUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ordencompra_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ordencompra);
      }
      if (PerrorTecnico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetOrdenesResponse other) {
      if (other == null) {
        return;
      }
      if (other.ordencompra_ != null) {
        if (ordencompra_ == null) {
          Ordencompra = new global::PROYCUATRO.OrdenesCompra();
        }
        Ordencompra.MergeFrom(other.Ordencompra);
      }
      if (other.PerrorTecnico.Length != 0) {
        PerrorTecnico = other.PerrorTecnico;
      }
      if (other.PerrorUsuario.Length != 0) {
        PerrorUsuario = other.PerrorUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (ordencompra_ == null) {
              Ordencompra = new global::PROYCUATRO.OrdenesCompra();
            }
            input.ReadMessage(Ordencompra);
            break;
          }
          case 18: {
            PerrorTecnico = input.ReadString();
            break;
          }
          case 26: {
            PerrorUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
