// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CResolucionOrden.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PROYCUATRO {

  /// <summary>Holder for reflection information generated from CResolucionOrden.proto</summary>
  public static partial class CResolucionOrdenReflection {

    #region Descriptor
    /// <summary>File descriptor for CResolucionOrden.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CResolucionOrdenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZDUmVzb2x1Y2lvbk9yZGVuLnByb3RvIqgBChBDUmVzb2x1Y2lvbk9yZGVu",
            "EhMKC2NvZF9lbXByZXNhGAEgASgJEhYKDnRpcF9yZXNvbHVjaW9uGAIgASgJ",
            "EhgKEG51bV9vcmRlbl9jb21wcmEYAyABKAkSGAoQbnVtX2F1dG9yaXphY2lv",
            "bhgEIAEoCRIZChFkZXNfb2JzZXJ2YWNpb25lcxgFIAEoCRIYChBtZW5zYWpl",
            "X3JlcHVlc3RhGAYgASgJIngKGlB1dENSZXNvbHVjaW9uT3JkZW5SZXF1ZXN0",
            "EiYKC0NSZXNvbHVjaW9uGAEgASgLMhEuQ1Jlc29sdWNpb25PcmRlbhIUCgxw",
            "Y29kX2VtcHJlc2EYAiABKAkSHAoUcGNvZF91c3VhcmlvX3dpbmRvd3MYAyAB",
            "KAkidQobUHV0Q1Jlc29sdWNpb25PcmRlblJlc3BvbnNlEiYKC0NSZXNvbHVj",
            "aW9uGAEgASgLMhEuQ1Jlc29sdWNpb25PcmRlbhIWCg5wZXJyb3JfdGVjbmlj",
            "bxgCIAEoCRIWCg5wZXJyb3JfdXN1YXJpbxgDIAEoCTJrChdDUmVzb2x1Y2lv",
            "bk9yZGVuU2VydmljZRJQChNQdXRDUmVzb2x1Y2lvbk9yZGVuEhsuUHV0Q1Jl",
            "c29sdWNpb25PcmRlblJlcXVlc3QaHC5QdXRDUmVzb2x1Y2lvbk9yZGVuUmVz",
            "cG9uc2VCCqoCB1BST1lET1NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.CResolucionOrden), global::PROYCUATRO.CResolucionOrden.Parser, new[]{ "CodEmpresa", "TipResolucion", "NumOrdenCompra", "NumAutorizacion", "DesObservaciones", "MensajeRepuesta" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.PutCResolucionOrdenRequest), global::PROYCUATRO.PutCResolucionOrdenRequest.Parser, new[]{ "CResolucion", "PcodEmpresa", "PcodUsuarioWindows" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PROYCUATRO.PutCResolucionOrdenResponse), global::PROYCUATRO.PutCResolucionOrdenResponse.Parser, new[]{ "CResolucion", "PerrorTecnico", "PerrorUsuario" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CResolucionOrden : pb::IMessage<CResolucionOrden> {
    private static readonly pb::MessageParser<CResolucionOrden> _parser = new pb::MessageParser<CResolucionOrden>(() => new CResolucionOrden());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CResolucionOrden> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CResolucionOrdenReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CResolucionOrden() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CResolucionOrden(CResolucionOrden other) : this() {
      codEmpresa_ = other.codEmpresa_;
      tipResolucion_ = other.tipResolucion_;
      numOrdenCompra_ = other.numOrdenCompra_;
      numAutorizacion_ = other.numAutorizacion_;
      desObservaciones_ = other.desObservaciones_;
      mensajeRepuesta_ = other.mensajeRepuesta_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CResolucionOrden Clone() {
      return new CResolucionOrden(this);
    }

    /// <summary>Field number for the "cod_empresa" field.</summary>
    public const int CodEmpresaFieldNumber = 1;
    private string codEmpresa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CodEmpresa {
      get { return codEmpresa_; }
      set {
        codEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tip_resolucion" field.</summary>
    public const int TipResolucionFieldNumber = 2;
    private string tipResolucion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TipResolucion {
      get { return tipResolucion_; }
      set {
        tipResolucion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_orden_compra" field.</summary>
    public const int NumOrdenCompraFieldNumber = 3;
    private string numOrdenCompra_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumOrdenCompra {
      get { return numOrdenCompra_; }
      set {
        numOrdenCompra_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_autorizacion" field.</summary>
    public const int NumAutorizacionFieldNumber = 4;
    private string numAutorizacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumAutorizacion {
      get { return numAutorizacion_; }
      set {
        numAutorizacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "des_observaciones" field.</summary>
    public const int DesObservacionesFieldNumber = 5;
    private string desObservaciones_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DesObservaciones {
      get { return desObservaciones_; }
      set {
        desObservaciones_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mensaje_repuesta" field.</summary>
    public const int MensajeRepuestaFieldNumber = 6;
    private string mensajeRepuesta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MensajeRepuesta {
      get { return mensajeRepuesta_; }
      set {
        mensajeRepuesta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CResolucionOrden);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CResolucionOrden other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CodEmpresa != other.CodEmpresa) return false;
      if (TipResolucion != other.TipResolucion) return false;
      if (NumOrdenCompra != other.NumOrdenCompra) return false;
      if (NumAutorizacion != other.NumAutorizacion) return false;
      if (DesObservaciones != other.DesObservaciones) return false;
      if (MensajeRepuesta != other.MensajeRepuesta) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CodEmpresa.Length != 0) hash ^= CodEmpresa.GetHashCode();
      if (TipResolucion.Length != 0) hash ^= TipResolucion.GetHashCode();
      if (NumOrdenCompra.Length != 0) hash ^= NumOrdenCompra.GetHashCode();
      if (NumAutorizacion.Length != 0) hash ^= NumAutorizacion.GetHashCode();
      if (DesObservaciones.Length != 0) hash ^= DesObservaciones.GetHashCode();
      if (MensajeRepuesta.Length != 0) hash ^= MensajeRepuesta.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CodEmpresa.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CodEmpresa);
      }
      if (TipResolucion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TipResolucion);
      }
      if (NumOrdenCompra.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumOrdenCompra);
      }
      if (NumAutorizacion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumAutorizacion);
      }
      if (DesObservaciones.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DesObservaciones);
      }
      if (MensajeRepuesta.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(MensajeRepuesta);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CodEmpresa);
      }
      if (TipResolucion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TipResolucion);
      }
      if (NumOrdenCompra.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumOrdenCompra);
      }
      if (NumAutorizacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumAutorizacion);
      }
      if (DesObservaciones.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DesObservaciones);
      }
      if (MensajeRepuesta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MensajeRepuesta);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CResolucionOrden other) {
      if (other == null) {
        return;
      }
      if (other.CodEmpresa.Length != 0) {
        CodEmpresa = other.CodEmpresa;
      }
      if (other.TipResolucion.Length != 0) {
        TipResolucion = other.TipResolucion;
      }
      if (other.NumOrdenCompra.Length != 0) {
        NumOrdenCompra = other.NumOrdenCompra;
      }
      if (other.NumAutorizacion.Length != 0) {
        NumAutorizacion = other.NumAutorizacion;
      }
      if (other.DesObservaciones.Length != 0) {
        DesObservaciones = other.DesObservaciones;
      }
      if (other.MensajeRepuesta.Length != 0) {
        MensajeRepuesta = other.MensajeRepuesta;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CodEmpresa = input.ReadString();
            break;
          }
          case 18: {
            TipResolucion = input.ReadString();
            break;
          }
          case 26: {
            NumOrdenCompra = input.ReadString();
            break;
          }
          case 34: {
            NumAutorizacion = input.ReadString();
            break;
          }
          case 42: {
            DesObservaciones = input.ReadString();
            break;
          }
          case 50: {
            MensajeRepuesta = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// client asking for all locations 
  /// </summary>
  public sealed partial class PutCResolucionOrdenRequest : pb::IMessage<PutCResolucionOrdenRequest> {
    private static readonly pb::MessageParser<PutCResolucionOrdenRequest> _parser = new pb::MessageParser<PutCResolucionOrdenRequest>(() => new PutCResolucionOrdenRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutCResolucionOrdenRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CResolucionOrdenReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenRequest(PutCResolucionOrdenRequest other) : this() {
      cResolucion_ = other.cResolucion_ != null ? other.cResolucion_.Clone() : null;
      pcodEmpresa_ = other.pcodEmpresa_;
      pcodUsuarioWindows_ = other.pcodUsuarioWindows_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenRequest Clone() {
      return new PutCResolucionOrdenRequest(this);
    }

    /// <summary>Field number for the "CResolucion" field.</summary>
    public const int CResolucionFieldNumber = 1;
    private global::PROYCUATRO.CResolucionOrden cResolucion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.CResolucionOrden CResolucion {
      get { return cResolucion_; }
      set {
        cResolucion_ = value;
      }
    }

    /// <summary>Field number for the "pcod_empresa" field.</summary>
    public const int PcodEmpresaFieldNumber = 2;
    private string pcodEmpresa_ = "";
    /// <summary>
    /// Codigo de empresa referenciada del core para el que se ejecuta el proceso,
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodEmpresa {
      get { return pcodEmpresa_; }
      set {
        pcodEmpresa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pcod_usuario_windows" field.</summary>
    public const int PcodUsuarioWindowsFieldNumber = 3;
    private string pcodUsuarioWindows_ = "";
    /// <summary>
    /// Codigo de usuario que ejecuta el proceso
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PcodUsuarioWindows {
      get { return pcodUsuarioWindows_; }
      set {
        pcodUsuarioWindows_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutCResolucionOrdenRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutCResolucionOrdenRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CResolucion, other.CResolucion)) return false;
      if (PcodEmpresa != other.PcodEmpresa) return false;
      if (PcodUsuarioWindows != other.PcodUsuarioWindows) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cResolucion_ != null) hash ^= CResolucion.GetHashCode();
      if (PcodEmpresa.Length != 0) hash ^= PcodEmpresa.GetHashCode();
      if (PcodUsuarioWindows.Length != 0) hash ^= PcodUsuarioWindows.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cResolucion_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CResolucion);
      }
      if (PcodEmpresa.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PcodUsuarioWindows);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cResolucion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CResolucion);
      }
      if (PcodEmpresa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodEmpresa);
      }
      if (PcodUsuarioWindows.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PcodUsuarioWindows);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutCResolucionOrdenRequest other) {
      if (other == null) {
        return;
      }
      if (other.cResolucion_ != null) {
        if (cResolucion_ == null) {
          CResolucion = new global::PROYCUATRO.CResolucionOrden();
        }
        CResolucion.MergeFrom(other.CResolucion);
      }
      if (other.PcodEmpresa.Length != 0) {
        PcodEmpresa = other.PcodEmpresa;
      }
      if (other.PcodUsuarioWindows.Length != 0) {
        PcodUsuarioWindows = other.PcodUsuarioWindows;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (cResolucion_ == null) {
              CResolucion = new global::PROYCUATRO.CResolucionOrden();
            }
            input.ReadMessage(CResolucion);
            break;
          }
          case 18: {
            PcodEmpresa = input.ReadString();
            break;
          }
          case 26: {
            PcodUsuarioWindows = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// response with all locations 
  /// </summary>
  public sealed partial class PutCResolucionOrdenResponse : pb::IMessage<PutCResolucionOrdenResponse> {
    private static readonly pb::MessageParser<PutCResolucionOrdenResponse> _parser = new pb::MessageParser<PutCResolucionOrdenResponse>(() => new PutCResolucionOrdenResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutCResolucionOrdenResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PROYCUATRO.CResolucionOrdenReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenResponse(PutCResolucionOrdenResponse other) : this() {
      cResolucion_ = other.cResolucion_ != null ? other.cResolucion_.Clone() : null;
      perrorTecnico_ = other.perrorTecnico_;
      perrorUsuario_ = other.perrorUsuario_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutCResolucionOrdenResponse Clone() {
      return new PutCResolucionOrdenResponse(this);
    }

    /// <summary>Field number for the "CResolucion" field.</summary>
    public const int CResolucionFieldNumber = 1;
    private global::PROYCUATRO.CResolucionOrden cResolucion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::PROYCUATRO.CResolucionOrden CResolucion {
      get { return cResolucion_; }
      set {
        cResolucion_ = value;
      }
    }

    /// <summary>Field number for the "perror_tecnico" field.</summary>
    public const int PerrorTecnicoFieldNumber = 2;
    private string perrorTecnico_ = "";
    /// <summary>
    /// Mensaje de error técnico del error ocurrido. Si todo está bien se retorna el valor 000000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorTecnico {
      get { return perrorTecnico_; }
      set {
        perrorTecnico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perror_usuario" field.</summary>
    public const int PerrorUsuarioFieldNumber = 3;
    private string perrorUsuario_ = "";
    /// <summary>
    /// En caso de ocurrir un error, se retorna el mensaje en len
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PerrorUsuario {
      get { return perrorUsuario_; }
      set {
        perrorUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutCResolucionOrdenResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutCResolucionOrdenResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CResolucion, other.CResolucion)) return false;
      if (PerrorTecnico != other.PerrorTecnico) return false;
      if (PerrorUsuario != other.PerrorUsuario) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (cResolucion_ != null) hash ^= CResolucion.GetHashCode();
      if (PerrorTecnico.Length != 0) hash ^= PerrorTecnico.GetHashCode();
      if (PerrorUsuario.Length != 0) hash ^= PerrorUsuario.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (cResolucion_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CResolucion);
      }
      if (PerrorTecnico.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PerrorUsuario);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (cResolucion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CResolucion);
      }
      if (PerrorTecnico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorTecnico);
      }
      if (PerrorUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PerrorUsuario);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutCResolucionOrdenResponse other) {
      if (other == null) {
        return;
      }
      if (other.cResolucion_ != null) {
        if (cResolucion_ == null) {
          CResolucion = new global::PROYCUATRO.CResolucionOrden();
        }
        CResolucion.MergeFrom(other.CResolucion);
      }
      if (other.PerrorTecnico.Length != 0) {
        PerrorTecnico = other.PerrorTecnico;
      }
      if (other.PerrorUsuario.Length != 0) {
        PerrorUsuario = other.PerrorUsuario;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (cResolucion_ == null) {
              CResolucion = new global::PROYCUATRO.CResolucionOrden();
            }
            input.ReadMessage(CResolucion);
            break;
          }
          case 18: {
            PerrorTecnico = input.ReadString();
            break;
          }
          case 26: {
            PerrorUsuario = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
