// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CResolucionOrden.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PROYCUATRO {
  public static partial class CResolucionOrdenService
  {
    static readonly string __ServiceName = "CResolucionOrdenService";

    static readonly grpc::Marshaller<global::PROYCUATRO.PutCResolucionOrdenRequest> __Marshaller_PutCResolucionOrdenRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.PutCResolucionOrdenRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PROYCUATRO.PutCResolucionOrdenResponse> __Marshaller_PutCResolucionOrdenResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PROYCUATRO.PutCResolucionOrdenResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PROYCUATRO.PutCResolucionOrdenRequest, global::PROYCUATRO.PutCResolucionOrdenResponse> __Method_PutCResolucionOrden = new grpc::Method<global::PROYCUATRO.PutCResolucionOrdenRequest, global::PROYCUATRO.PutCResolucionOrdenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PutCResolucionOrden",
        __Marshaller_PutCResolucionOrdenRequest,
        __Marshaller_PutCResolucionOrdenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PROYCUATRO.CResolucionOrdenReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CResolucionOrdenService</summary>
    [grpc::BindServiceMethod(typeof(CResolucionOrdenService), "BindService")]
    public abstract partial class CResolucionOrdenServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::PROYCUATRO.PutCResolucionOrdenResponse> PutCResolucionOrden(global::PROYCUATRO.PutCResolucionOrdenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CResolucionOrdenService</summary>
    public partial class CResolucionOrdenServiceClient : grpc::ClientBase<CResolucionOrdenServiceClient>
    {
      /// <summary>Creates a new client for CResolucionOrdenService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CResolucionOrdenServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CResolucionOrdenService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CResolucionOrdenServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CResolucionOrdenServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CResolucionOrdenServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PROYCUATRO.PutCResolucionOrdenResponse PutCResolucionOrden(global::PROYCUATRO.PutCResolucionOrdenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutCResolucionOrden(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PROYCUATRO.PutCResolucionOrdenResponse PutCResolucionOrden(global::PROYCUATRO.PutCResolucionOrdenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PutCResolucionOrden, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PROYCUATRO.PutCResolucionOrdenResponse> PutCResolucionOrdenAsync(global::PROYCUATRO.PutCResolucionOrdenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutCResolucionOrdenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PROYCUATRO.PutCResolucionOrdenResponse> PutCResolucionOrdenAsync(global::PROYCUATRO.PutCResolucionOrdenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PutCResolucionOrden, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CResolucionOrdenServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CResolucionOrdenServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CResolucionOrdenServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PutCResolucionOrden, serviceImpl.PutCResolucionOrden).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CResolucionOrdenServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PutCResolucionOrden, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PROYCUATRO.PutCResolucionOrdenRequest, global::PROYCUATRO.PutCResolucionOrdenResponse>(serviceImpl.PutCResolucionOrden));
    }

  }
}
#endregion
