// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TiempoEspera.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class TiempoEsperaService
{
  static readonly string __ServiceName = "TiempoEsperaService";

  static readonly grpc::Marshaller<global::TiempoEsperaRequest> __Marshaller_TiempoEsperaRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TiempoEsperaRequest.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::TiempoEspera> __Marshaller_TiempoEspera = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TiempoEspera.Parser.ParseFrom);

  static readonly grpc::Method<global::TiempoEsperaRequest, global::TiempoEspera> __Method_GetTiempoEspera = new grpc::Method<global::TiempoEsperaRequest, global::TiempoEspera>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetTiempoEspera",
      __Marshaller_TiempoEsperaRequest,
      __Marshaller_TiempoEspera);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::TiempoEsperaReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of TiempoEsperaService</summary>
  [grpc::BindServiceMethod(typeof(TiempoEsperaService), "BindService")]
  public abstract partial class TiempoEsperaServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::TiempoEspera> GetTiempoEspera(global::TiempoEsperaRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for TiempoEsperaService</summary>
  public partial class TiempoEsperaServiceClient : grpc::ClientBase<TiempoEsperaServiceClient>
  {
    /// <summary>Creates a new client for TiempoEsperaService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public TiempoEsperaServiceClient(grpc::Channel channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for TiempoEsperaService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public TiempoEsperaServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected TiempoEsperaServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected TiempoEsperaServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::TiempoEspera GetTiempoEspera(global::TiempoEsperaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetTiempoEspera(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::TiempoEspera GetTiempoEspera(global::TiempoEsperaRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetTiempoEspera, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::TiempoEspera> GetTiempoEsperaAsync(global::TiempoEsperaRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetTiempoEsperaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::TiempoEspera> GetTiempoEsperaAsync(global::TiempoEsperaRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetTiempoEspera, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override TiempoEsperaServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new TiempoEsperaServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(TiempoEsperaServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetTiempoEspera, serviceImpl.GetTiempoEspera).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, TiempoEsperaServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetTiempoEspera, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TiempoEsperaRequest, global::TiempoEspera>(serviceImpl.GetTiempoEspera));
  }

}
#endregion
