// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TiempoEspera.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from TiempoEspera.proto</summary>
public static partial class TiempoEsperaReflection {

  #region Descriptor
  /// <summary>File descriptor for TiempoEspera.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TiempoEsperaReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJUaWVtcG9Fc3BlcmEucHJvdG8iKQoTVGllbXBvRXNwZXJhUmVxdWVzdBIS",
          "CgplbXByZXNhX2lkGAEgASgJIh8KDFRpZW1wb0VzcGVyYRIPCgdtaW51dG9z",
          "GAEgASgJMk0KE1RpZW1wb0VzcGVyYVNlcnZpY2USNgoPR2V0VGllbXBvRXNw",
          "ZXJhEhQuVGllbXBvRXNwZXJhUmVxdWVzdBoNLlRpZW1wb0VzcGVyYWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::TiempoEsperaRequest), global::TiempoEsperaRequest.Parser, new[]{ "EmpresaId" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::TiempoEspera), global::TiempoEspera.Parser, new[]{ "Minutos" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class TiempoEsperaRequest : pb::IMessage<TiempoEsperaRequest> {
  private static readonly pb::MessageParser<TiempoEsperaRequest> _parser = new pb::MessageParser<TiempoEsperaRequest>(() => new TiempoEsperaRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<TiempoEsperaRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TiempoEsperaReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEsperaRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEsperaRequest(TiempoEsperaRequest other) : this() {
    empresaId_ = other.empresaId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEsperaRequest Clone() {
    return new TiempoEsperaRequest(this);
  }

  /// <summary>Field number for the "empresa_id" field.</summary>
  public const int EmpresaIdFieldNumber = 1;
  private string empresaId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string EmpresaId {
    get { return empresaId_; }
    set {
      empresaId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as TiempoEsperaRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(TiempoEsperaRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EmpresaId != other.EmpresaId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (EmpresaId.Length != 0) hash ^= EmpresaId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (EmpresaId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(EmpresaId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (EmpresaId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EmpresaId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(TiempoEsperaRequest other) {
    if (other == null) {
      return;
    }
    if (other.EmpresaId.Length != 0) {
      EmpresaId = other.EmpresaId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          EmpresaId = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class TiempoEspera : pb::IMessage<TiempoEspera> {
  private static readonly pb::MessageParser<TiempoEspera> _parser = new pb::MessageParser<TiempoEspera>(() => new TiempoEspera());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<TiempoEspera> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TiempoEsperaReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEspera() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEspera(TiempoEspera other) : this() {
    minutos_ = other.minutos_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public TiempoEspera Clone() {
    return new TiempoEspera(this);
  }

  /// <summary>Field number for the "minutos" field.</summary>
  public const int MinutosFieldNumber = 1;
  private string minutos_ = "";
  /// <summary>
  ///string last_name = 2;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Minutos {
    get { return minutos_; }
    set {
      minutos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as TiempoEspera);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(TiempoEspera other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Minutos != other.Minutos) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Minutos.Length != 0) hash ^= Minutos.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Minutos.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Minutos);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Minutos.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Minutos);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(TiempoEspera other) {
    if (other == null) {
      return;
    }
    if (other.Minutos.Length != 0) {
      Minutos = other.Minutos;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Minutos = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
